.TH "include Directory Reference" 3 "Sun Apr 9 2023" "ng-deck" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBControls\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBCommunicator\&.h\fP"
.br
.RI "communicate with PC via Serial "
.ti -1c
.RI "file \fBDisplay\&.h\fP"
.br
.RI "Wrapper for Arduino I2C display\&. "
.ti -1c
.RI "file \fBList\&.h\fP"
.br
.RI "Contains and manipulate list of projects This class contains an array of Strigns which is an projects received from Service and allows to get projects to output on display\&. "
.ti -1c
.RI "file \fBState_Enum\&.h\fP"
.br
.RI "Enum of program states\&. "
.ti -1c
.RI "file \fBStateManager\&.h\fP"
.br
.RI "program state manager "
.in -1c
