.TH "include/Controls Directory Reference" 3 "Sun Apr 9 2023" "ng-deck" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Controls Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBButton\&.h\fP"
.br
.RI "Wrapper for button\&. "
.ti -1c
.RI "file \fBButtonsProcessor\&.h\fP"
.br
.RI "Handle buttons\&. "
.ti -1c
.RI "file \fBJoyProcessor\&.h\fP"
.br
.RI "Handle joystick\&. "
.in -1c
