.TH "include/Controls/Button.h" 3 "Sun Apr 9 2023" "ng-deck" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Controls/Button.h \- Wrapper for button\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBButton\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBBUTTON_H\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Wrapper for button\&. 

facilitates the handling of button presses 
.PP
Definition in file \fBButton\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define BUTTON_H"

.PP
Definition at line \fB6\fP of file \fBButton\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ng-deck from the source code\&.
