.TH "include/Controls/JoyProcessor.h" 3 "Sun Apr 9 2023" "ng-deck" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Controls/JoyProcessor.h \- Handle joystick\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBJoyProcessor\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBJoyPin\fP   A1"
.br
.ti -1c
.RI "#define \fBJOY_PROCESSOR_H\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Handle joystick\&. 


.PP
Definition in file \fBJoyProcessor\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define JOY_PROCESSOR_H"

.PP
Definition at line \fB9\fP of file \fBJoyProcessor\&.h\fP\&.
.SS "#define JoyPin   A1"

.PP
Definition at line \fB4\fP of file \fBJoyProcessor\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ng-deck from the source code\&.
