.TH "include/StateManager.h" 3 "Sun Apr 9 2023" "ng-deck" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/StateManager.h \- program state manager  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBStateManager\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSTATE_MANAGER_H\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
program state manager 

Global class to manage state of program 
.PP
Definition in file \fBStateManager\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define STATE_MANAGER_H"

.PP
Definition at line \fB7\fP of file \fBStateManager\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ng-deck from the source code\&.
